const members = [
    {
        id:1,
        name:'yashvant',
        email:'yashvant@gmail.com',
        status:'active'
    },
    {
        id:2,
        name:'pranav',
        email:'pranav@gmail.com',
        status:'inactive'
    },
    {
        id:3,
        name:'david',
        email:'david@gmail.com',
        status:'active'
    },
    {
        id:4,
        name:'sagar',
        email:'sagar@gmail.com',
        status:'inactive'
    },
    {
        id:5,
        name:'ryan',
        email:'ryan@gmail.com',
        status:'inactive'
    },
    {
        id:6,
        name:'jack',
        email:'jack@gmail.com',
        status:'inactive'
    }   
];

module.exports = members;